Task 1: Create Employee DataFrame
Create a pandas DataFrame using the employee data.

In [24]:
import pandas as pd

In [25]:
import pandas as pd

data = {
    "EmployeeID": [201,202,203,204,205,206,207,208,209,210],
    "Name": ["Sarah","Michael","Jennifer","David","Lisa","James","Emma","Robert","Sophia","William"],
    "Department": ["Engineering","Sales","Marketing","Engineering","HR","Sales","Engineering","Marketing","Sales","HR"],
    "Salary": [85000,62000,71000,92000,58000,68000,78000,75000,65000,60000],
    "Performance Score": [4,3,5,5,4,4,3,4,5,3],
    "Years of Service": [5,3,7,8,4,6,2,5,4,3]
}
df = pd.DataFrame(data)
# Set EmployeeID as index
df.set_index("EmployeeID", inplace=True)
df

                Name   Department  Salary  Performance Score  Years of Service
EmployeeID
201            Sarah  Engineering   85000                  4                 5
202          Michael        Sales   62000                  3                 3
203         Jennifer    Marketing   71000                  5                 7
204            David  Engineering   92000                  5                 8
205             Lisa           HR   58000                  4                 4
206            James        Sales   68000                  4                 6
207             Emma  Engineering   78000                  3                 2
208           Robert    Marketing   75000                  4                 5
209           Sophia        Sales   65000                  5                 4
210          William           HR   60000                  3                 3

Task 2: Select Specific Columns
Select and display only the 'Name', 'Department', and 'Salary' columns

In [26]:
df[["Name", "Department", "Salary"]]

                Name   Department  Salary
EmployeeID
201            Sarah  Engineering   85000
202          Michael        Sales   62000
203         Jennifer    Marketing   71000
204            David  Engineering   92000
205             Lisa           HR   58000
206            James        Sales   68000
207             Emma  Engineering   78000
208           Robert    Marketing   75000
209           Sophia        Sales   65000
210          William           HR   60000

Task 3: Use iloc to display the employee at row position 5

In [27]:
df.iloc[5]

Name                 James
Department           Sales
Salary               68000
Performance Score        4
Years of Service         6
Name: 206, dtype: object

Task 4:Use loc to display the employee whose EmployeeID is 208.

In [28]:
df.loc[208]

Name                    Robert
Department           Marketing
Salary                   75000
Performance Score            4
Years of Service             5
Name: 208, dtype: object

Task 5: Filter and display all employees from the 'Engineering' department

In [29]:
engineering_employees = df[df["Department"] == "Engineering"]
engineering_employees

             Name   Department  Salary  Performance Score  Years of Service
EmployeeID
201         Sarah  Engineering   85000                  4                 5
204         David  Engineering   92000                  5                 8
207          Emma  Engineering   78000                  3                 2

Task 6: Filter employees with Salary greater than 70000

In [30]:
high_salary = df[df["Salary"] > 70000]
high_salary

                Name   Department  Salary  Performance Score  Years of Service
EmployeeID
201            Sarah  Engineering   85000                  4                 5
203         Jennifer    Marketing   71000                  5                 7
204            David  Engineering   92000                  5                 8
207             Emma  Engineering   78000                  3                 2
208           Robert    Marketing   75000                  4                 5

Task 7: Filter employees from 'Sales' department with Performance Score ≥ 4

In [31]:
sales_high_perf = df[(df["Department"] == "Sales") & (df["Performance Score"] >= 4)]
sales_high_perf

              Name Department  Salary  Performance Score  Years of Service
EmployeeID
206          James      Sales   68000                  4                 6
209         Sophia      Sales   65000                  5                 4

Task 8: Sort DataFrame by Salary (Descending) and Show Top 3 Highest-Paid Employees

In [32]:
top_3_highest = df.sort_values(by="Salary", ascending=False).head(3)
top_3_highest

             Name   Department  Salary  Performance Score  Years of Service
EmployeeID
204         David  Engineering   92000                  5                 8
201         Sarah  Engineering   85000                  4                 5
207          Emma  Engineering   78000                  3                 2

Task 9: Sort by Department (Ascending) and Salary (Descending)

In [33]:
sorted_df = df.sort_values(by=["Department", "Salary"], ascending=[True, False])
sorted_df

                Name   Department  Salary  Performance Score  Years of Service
EmployeeID
204            David  Engineering   92000                  5                 8
201            Sarah  Engineering   85000                  4                 5
207             Emma  Engineering   78000                  3                 2
210          William           HR   60000                  3                 3
205             Lisa           HR   58000                  4                 4
208           Robert    Marketing   75000                  4                 5
203         Jennifer    Marketing   71000                  5                 7
206            James        Sales   68000                  4                 6
209           Sophia        Sales   65000                  5                 4
202          Michael        Sales   62000                  3                 3